input {
  syslog {
    port => 5000
    type => "syslog"
  }
  tcp {
    port => 5000
    type => "docker"
    codec => "json"
  }
}

filter {
  if [type] == "docker" {
    mutate {
      add_field => { "[@metadata][index_name]" => "docker-%{+YYYY.MM.dd}" }
    }
  }
  
  if [type] == "syslog" {
    mutate {
      add_field => { "[@metadata][index_name]" => "syslog-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index_name]}"
    user => "elastic"
    password => "changeme"
  }
  
  stdout {
    codec => rubydebug
  }
}
